const player = "p"
const meat = "m"
const cheese = "c"
const tomato = "t"
const lettuce = "l"
const topBun = "b"

setLegend(
  [ player, bitmap`
................
................
................
................
................
................
................
................
................
................
..CCCCCCCCCCCC..
...CCCCCCCCCC...
....CCCCCCCC....
................
................
................` ],
  [ meat, bitmap`
................
................
................
................
................
................
...C0CC0CC03C...
..C0CC0CC0CC0C..
..0CC0C30CC0CC..
...C0CC0C30CC...
................
................
................
................
................
................`],
  [ cheese, bitmap`
................
................
................
................
................
.........66.....
.......666666...
.....666666666..
...666666666666.
..66666666666...
....6666666.....
......666.......
................
................
................
................`],
  [ tomato, bitmap`
................
................
................
................
................
................
................
....3333333333..
...332322232333.
...333232323233.
....3333333333..
................
................
................
................
................`],
  [ lettuce, bitmap`
................
................
................
................
.......DF..DD...
...DF.DDDDDD....
..DDDD44D4DDDF..
....FD4D4DD4DF..
..DDDDDDD4DDDD..
...FDD.DDDDD....
.......D..FF....
................
................
................
................
................`],
  [ topBun, bitmap`
................
................
................
.....CCCC2C.....
....CC6C6CCC....
...C6CCCCC6CC...
..CCC2C6CCC2CC..
..CCCCCCCCCCCC..
................
................
................
................
................
................
................
................`]
)

setSolids([player, meat, cheese, tomato, lettuce, topBun])

let level = 0
const levels = [
  map`
.....
.....
.....
.....
..p..`
]

setMap(levels[level])

setPushables({
  [ player ]: []
})

onInput("a", () => {
  getFirst(player).x -= 1
})

onInput("d", () => {
  getFirst(player).x += 1
})
/*
function addSprite(x, y, spriteType) {
  return {
    type: spriteType,
    x: x,
    y: y,
  };
}
*/
function randFood() {
  let num = Math.floor(Math.random() * 5 + 1)
  if (num == 1)
    return meat;
  else if (num == 2)
    return cheese;
  else if (num == 3)
    return tomato;
  else if (num == 4)
    return lettuce;
  else
    return topBun;
}

let foods = [];

function addFood() {
  let x = Math.floor(Math.random() * 5);
  let y = 0;
  let newFood = addSprite(x, y, randFood());
  foods.push(newFood);
}

function fallingFood() {
  getAll(foods).forEach((food) => {
    food.y += 1;
  });
}

function removeFood() {
  getAll(foods).forEach((food) => {
    if (food.y >= 5) {
      let x = food.x;
      let y = food.y;
      food.remove();
      clearTile(x, y);
    }
  });
}

var runGame = setInterval(() => {
  addFood();
  fallingFood();
  removeFood();
}, 1000);
